[project]
name = "nlp-cc0c2"
version = "0.1.0"
description = "Pc1 de nlp con Lara"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.6",
    "numpy>=2.3.3",
    "pandas>=2.3.2",
    "pip>=25.2",
    "spacy>=3.8.7",
]
